### ISSUE TITLE
JSON parsing issue in TD version > 16600

### ISSUE THREAD

**Issue by kellyvigil** [BarakChamo/TD_PoseNet#1]
Thanks for releasing this. I get an issue osc_callbacks dat seen in the attached image and here below. This is not an issue in TD version 16600 (and might assume earlier builds too, but only tested on 16600 vs 17550 and 18360).

Traceback (most recent call last):
  File "/project1/posenet_osc/osc_callbacks", line 15, in onReceiveOSC
  File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1900 (char 1899)

<img width="908" alt="Screen Shot 2019-08-12 at 2 18 33 PM" src="https://user-images.githubusercontent.com/5696281/62894347-8df5b400-bd1a-11e9-9868-34165fbfa8be.png">

**Comment by cyiorkouni** [comment]
@kellyvigil did you have any luck sorting this issue? I have a similar problem. Thx

**Comment by BibiPush** [comment]
> Thanks for releasing this. I get an issue osc_callbacks dat seen in the attached image and here below. This is not an issue in TD version 16600 (and might assume earlier builds too, but only tested on 16600 vs 17550 and 18360).
> 
> Traceback (most recent call last):
> File "/project1/posenet_osc/osc_callbacks", line 15, in onReceiveOSC
> File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/**init**.py", line 319, in loads
> return _default_decoder.decode(s)
> File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 342, in decode
> raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 1900 (char 1899)
> 
> <img alt="Screen Shot 2019-08-12 at 2 18 33 PM" width="908" src="https://user-images.githubusercontent.com/5696281/62894347-8df5b400-bd1a-11e9-9868-34165fbfa8be.png">

I confirm I have the same issue.

**Comment by webbrain-one** [comment]
Thanks for reporting this! I’ve opened a pull request (https://github.com/BarakChamo/TD_PoseNet/pull/5) to fix the JSON parsing issue in TD versions newer than 16600 that is causing the `json.decoder.JSONDecodeError: Extra data` error in `osc_callbacks`.
